name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
   
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy with Docker
      run: |
        ssh -T -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
        echo "Connection successful!"
        [ -d raghad ] || mkdir raghad
        cd raghad
        echo "I am in the raghad dir!"
        
        docker --version || { echo "Docker is not installed!"; exit 1; }
        
        docker pull nginx || { echo "Docker pull failed!"; exit 1; }
        echo "Docker image pulled successfully."

        
        docker run -d -p 80:80 --name my_nginx_container nginx || { echo "Docker run failed!"; exit 1; }
        
        echo "Docker container started successfully!"
        EOF
