name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3


    - name: Setup SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        
    - name: Deploy with Docker
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}<< 'EOF'      
        cd raghad

        docker pull nginx:latest

        docker stop nginx_container || true
        docker rm nginx_container || true

        docker run -d --name nginx_container -p 80:80 nginx:latest
        EOF
